;this file for FamiTone4.2 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


fireflies_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Fireflies

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $70 ;instrument $09
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c4,$c4,$c3,$c3,$c2,$c1,$c0,$00
	.byte $0e
@env2:
	.byte $c2,$c3,$c5,$c6,$c7,$c8,$05,$c7,$c3,$00,$08
@env3:
	.byte $cf,$c9,$c8,$c7,$04,$c6,$02,$c5,$02,$c4,$c4,$c3,$00,$0b
@env4:
	.byte $cd,$cc,$cb,$ca,$c9,$c9,$c8,$02,$c7,$c7,$c6,$c5,$c5,$c4,$00,$0d


; Fireflies
@song0ch0:
	.byte $fb,$05
@ref0:
	.byte $97,$82,$32,$81,$39,$85,$39,$85,$37,$81,$39,$85,$37,$85
@ref1:
	.byte $32,$95,$32,$81,$34,$85,$34,$85,$32,$81,$34,$85,$37,$85
@ref2:
	.byte $39,$95,$3b,$85,$39,$85,$37,$81,$32,$85,$32,$81,$32,$85
@ref3:
	.byte $39,$81,$37,$85,$34,$b1
@song0ch0loop:
	.byte $ff,$0d
	.word @ref0
@ref5:
	.byte $32,$95,$34,$85,$34,$85,$32,$85,$34,$81,$37,$85,$39,$81
@ref6:
	.byte $87,$32,$81,$32,$85,$3b,$89,$39,$85,$37,$81,$32,$85,$32,$81,$3b
	.byte $85
@ref7:
	.byte $39,$85,$34,$91,$37,$a1
@ref8:
	.byte $97,$3b,$85,$39,$85,$37,$81,$3e,$85,$3b,$89
@ref9:
	.byte $39,$85,$37,$81,$39,$a9,$32,$85
@ref10:
	.byte $37,$85,$36,$81,$34,$a1,$84,$26,$8d
@ref11:
	.byte $8f,$2a,$9d,$28,$8d
@ref12:
	.byte $8f,$28,$85,$82,$34,$81,$37,$89,$3b,$85,$84,$2d,$81,$82,$37,$89
@ref13:
	.byte $32,$85,$32,$81,$34,$81,$84,$24,$85,$82,$34,$85,$37,$85,$39,$81
	.byte $34,$81,$84,$28,$8d
@ref14:
	.byte $8b,$82,$32,$81,$84,$28,$85,$82,$37,$81,$37,$89,$3b,$85,$84,$2d
	.byte $81,$82,$37,$89
@ref15:
	.byte $32,$85,$37,$85,$84,$2d,$9d,$82,$34,$8d
@ref16:
	.byte $97,$32,$81,$39,$85,$39,$85,$37,$81,$39,$85,$37,$85
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$0e
	.word @ref2
@ref19:
	.byte $39,$81,$37,$85,$86,$26,$89,$28,$85,$2b,$85,$26,$81,$28,$85,$2b
	.byte $85,$26,$81
	.byte $fd
	.word @song0ch0loop

; Fireflies
@song0ch1:
@ref20:
	.byte $97,$80,$26,$81,$2d,$85,$2d,$85,$2b,$81,$2d,$85,$2b,$85
@ref21:
	.byte $26,$95,$26,$81,$28,$85,$28,$85,$26,$81,$28,$85,$2b,$85
@ref22:
	.byte $2d,$95,$2f,$85,$2d,$85,$2b,$81,$26,$85,$26,$81,$26,$85
@ref23:
	.byte $2d,$81,$2b,$b9
@song0ch1loop:
	.byte $ff,$0d
	.word @ref20
@ref25:
	.byte $26,$95,$28,$85,$28,$85,$26,$85,$28,$81,$2b,$85,$2d,$81
@ref26:
	.byte $87,$26,$81,$26,$85,$2f,$89,$2d,$85,$2b,$81,$26,$85,$26,$81,$2f
	.byte $85
@ref27:
	.byte $2d,$85,$28,$91,$2b,$a1
@ref28:
	.byte $97,$2f,$85,$2d,$85,$2b,$81,$32,$85,$2f,$89
@ref29:
	.byte $2d,$85,$2b,$81,$2d,$a9,$26,$85
@ref30:
	.byte $2b,$85,$2a,$81,$28,$81,$84,$30,$9d,$2f,$8d
@ref31:
	.byte $8f,$26,$9d,$24,$8d
@ref32:
	.byte $8f,$2f,$9d,$2b,$8d
@ref33:
	.byte $8f,$30,$8d,$32,$8d,$34,$8d
@ref34:
	.byte $8f,$30,$9d,$2f,$8d
@ref35:
	.byte $8f,$31,$9d,$80,$28,$8d
@ref36:
	.byte $97,$26,$81,$2d,$85,$2d,$85,$2b,$81,$2d,$85,$2b,$85
	.byte $ff,$0e
	.word @ref21
	.byte $ff,$0e
	.word @ref22
@ref39:
	.byte $2d,$81,$2b,$b9
	.byte $fd
	.word @song0ch1loop

; Fireflies
@song0ch2:
@ref40:
	.byte $8d,$00,$81,$82,$26,$87,$26,$95,$00,$81,$2b,$85
@ref41:
	.byte $8b,$00,$81,$24,$89,$24,$89,$24,$8d,$24,$85
@ref42:
	.byte $87,$00,$81,$24,$81,$26,$89,$26,$95,$00,$81,$2b,$85
@ref43:
	.byte $83,$2b,$89,$24,$89,$24,$8d,$24,$85,$2b,$81,$24,$85
@song0ch2loop:
@ref44:
	.byte $87,$82,$28,$85,$26,$89,$26,$95,$00,$81,$2b,$85
	.byte $ff,$0b
	.word @ref41
@ref46:
	.byte $87,$00,$81,$28,$81,$26,$89,$26,$95,$00,$81,$2b,$85
@ref47:
	.byte $83,$2b,$89,$24,$ab,$00
@ref48:
	.byte $8b,$00,$81,$84,$24,$9d,$23,$8d
@ref49:
	.byte $8f,$26,$ad
@ref50:
	.byte $8f,$24,$9d,$23,$8d
	.byte $ff,$05
	.word @ref31
@ref52:
	.byte $8f,$24,$9d,$24,$8d
@ref53:
	.byte $8f,$24,$8d,$26,$8d,$28,$8d
	.byte $ff,$05
	.word @ref50
@ref55:
	.byte $8f,$25,$ad
	.byte $ff,$0b
	.word @ref40
	.byte $ff,$0b
	.word @ref41
	.byte $ff,$0d
	.word @ref42
	.byte $ff,$0d
	.word @ref43
	.byte $fd
	.word @song0ch2loop

; Fireflies
@song0ch3:
@ref60:
	.byte $bf
@ref61:
	.byte $bf
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@song0ch3loop:
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
@ref70:
	.byte $bf
@ref71:
	.byte $bf
@ref72:
	.byte $bf
@ref73:
	.byte $bf
@ref74:
	.byte $bf
@ref75:
	.byte $bf
@ref76:
	.byte $bf
@ref77:
	.byte $bf
@ref78:
	.byte $bf
@ref79:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

; Fireflies
@song0ch4:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@song0ch4loop:
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
