;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2

@sfx_ntsc_0:
	.byte $89,$3f,$8a,$8b,$01,$00
@sfx_pal_0:
	.byte $89,$3f,$8a,$8b,$01,$00
@sfx_ntsc_1:
	.byte $89,$3f,$8a,$8f,$01,$00
@sfx_pal_1:
	.byte $89,$3f,$8a,$8f,$01,$00
@sfx_ntsc_2:
	.byte $89,$3f,$8a,$8d,$01,$00
@sfx_pal_2:
	.byte $89,$3f,$8a,$8d,$01,$00
